// app/utils/skill-image.js

// Named export for skills data
export const skillsData = [
  'HTML',
  'CSS',
  'Javascript',
  'React',
  'Next JS',
  'Nuxt JS',
  'Node JS',
  'Vue',
  'Angular',
  'Docker',
  'Photoshop',
  'Illustrator',
  'Svelte',
  'GCP',
  'Azure',
  'Fastify',
  'Haxe',
  'Ionic',
  'Markdown',
  'Microsoft Office',
  'Picsart',
  'Sketch',
  'Unity',
  'WolframAlpha',
  'Adobe XD',
  'After Effects',
  'Bootstrap',
  'Bulma',
  'CapacitorJs',
  'Coffeescript',
  'MemSQL',
  'C',
  'C++',
  'C#',
  'Python',
  'Java',
  'Julia',
  'Matlab',
  'Swift',
  'Ruby',
  'Kotlin',
  'Go',
  'PHP',
  'Flutter',
  'Dart',
  'Typescript',
  'Git',
  'Figma',
  'Canva',
  'Ubuntu',
  'MongoDB',
  'Tailwind',
  'ViteJS',
  'VuetifyJS',
  'MySQL',
  'PostgreSQL',
  'Prisma',
  'AWS',
  'Firebase',
  'Blender',
  'Premiere Pro',
  'Adobe Audition',
  'Deno',
  'Django',
  'Gimp',
  'Graphql',
  'Lightroom',
  'MaterialUI',
  'Nginx',
  'Numpy',
  'OpenCV',
  'Pytorch',
  'Selenium',
  'Strapi',
  'Tensorflow',
  'Webex',
  'Wordpress',
  'Pandas',
  'Scikit Learn',
  '.NET',
  '.NET Core',
  'Kubernetes',
  'Linux',
  'SQLAlchemy',
  'FastAPI',
];

// Named export for image URL helper
export const skillsImage = (skill) => {
  // Map of exceptions where the default normalization wouldn't match filenames
  const exceptions = {
    'c++': 'cplus',
    'c#': 'csharp',
    '.net': 'net',
    '.net core': 'net-core',
    'scikit learn': 'scikit-learn',
    'adobe xd': 'adobe-xd',
    'after effects': 'after-effects',
    'microsoft office': 'microsoft-office',
    'premiere pro': 'premiere-pro',
    'adobe audition': 'adobe-audition',
    'next js': 'next-js',
    'nuxt js': 'nuxt-js',
    'vitejs': 'vitejs', // keep as-is
    'vuetifyjs': 'vuetifyjs', // keep as-is
  };

  const key = skill.toLowerCase();
  const fileName = exceptions[key] || key.replace(/\s+/g, '-').replace(/\./g, '');
  return `/skills/${fileName}.svg`;
};
